theme: jekyll-theme-slate
title: Juan Pablo's homepage
description: This is the main portal for my Github Pages, here i wll record topics that are interesting to me, like reading, watching cute animals and learning chinese. Of course, using my botched english.
